//
// Generated file, do not edit! Created by opp_msgc 4.5 from DIF/EFCP/FCTimers.msg.
//

#ifndef _FCTIMERS_M_H_
#define _FCTIMERS_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>DIF/EFCP/FCTimers.msg</tt> by opp_msgc.
 * <pre>
 * enum FCTimerType
 * {
 *   FC_SENDING_RATE_TIMER = 1;
 *   
 * }
 * </pre>
 */
enum FCTimerType {
    FC_SENDING_RATE_TIMER = 1
};

/**
 * Class generated from <tt>DIF/EFCP/FCTimers.msg</tt> by opp_msgc.
 * <pre>
 * message FCTimers {
 *     int type enum(FCTimerType);
 *     string anotherField;
 *     double arrayField1[];
 *     double arrayField2[10];
 * }
 * </pre>
 */
class FCTimers : public ::cMessage
{
  protected:
    int type_var;
    opp_string anotherField_var;
    double *arrayField1_var; // array ptr
    unsigned int arrayField1_arraysize;
    double arrayField2_var[10];

  private:
    void copy(const FCTimers& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FCTimers&);

  public:
    FCTimers(const char *name=NULL, int kind=0);
    FCTimers(const FCTimers& other);
    virtual ~FCTimers();
    FCTimers& operator=(const FCTimers& other);
    virtual FCTimers *dup() const {return new FCTimers(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getType() const;
    virtual void setType(int type);
    virtual const char * getAnotherField() const;
    virtual void setAnotherField(const char * anotherField);
    virtual void setArrayField1ArraySize(unsigned int size);
    virtual unsigned int getArrayField1ArraySize() const;
    virtual double getArrayField1(unsigned int k) const;
    virtual void setArrayField1(unsigned int k, double arrayField1);
    virtual unsigned int getArrayField2ArraySize() const;
    virtual double getArrayField2(unsigned int k) const;
    virtual void setArrayField2(unsigned int k, double arrayField2);
};

inline void doPacking(cCommBuffer *b, FCTimers& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, FCTimers& obj) {obj.parsimUnpack(b);}


#endif // _FCTIMERS_M_H_
